### ISSUE TITLE
Errors installing on todays node v

### ISSUE THREAD

**Issue by getsetbro** [rhaker/react-native-play-audio-ios#2]
I was hoping to use this npm but I received these errors during install:
https://gist.github.com/getsetbro/4f8115ed62a3ae9b9880
Could it be updated or let me know of a work around?

**Comment by rhaker** [comment]
Just updated the package.json to the latest versions. I was able to install with no problems - so it should work for you. Make sure you have the latest node/brew/react-native/etc... installed. Good luck.

**Comment by getsetbro** [comment]
Thanks. Is this capable of changing the volume audio that it is playing?

**Comment by rhaker** [comment]
Volume is always tricky because the user's device may be on low/high/mute/etc. Currently, the module doesn't support volume, but it's something I might add in the future. Feel free to fork the code and add it yourself, too.
