### ISSUE TITLE
"File does not exist in app documents directory."

### ISSUE THREAD

**Issue by getsetbro** [rhaker/react-native-play-audio-ios#3]
How do I put my .mp3s where this can play them?

**Comment by rhaker** [comment]
The short answer is that the audio file must exist in the documents directory (for this module). And the documents directory isn't available directly through Xcode. So you have several options:

1) You can copy/write a preloaded file to the documents directory. And then you can play it. To copy a preloaded file from your resources bundle, you can use the react-native-fs module.

2) If you are creating the audio file you want to play in the app, make sure to create it in the documents directory. This was what I was doing (recording audio, then playing it). If you use react-native-record-audio-ios, the recording is saved directly into the documents directory.

3) You can see if react-native-audio by jsierles works for your needs. I haven't really investigated it. It might be what you are looking for.

In the future, I might add the "copy from resources bundle step" into the module. But, don't know when I'll get around to it. Might be some time. Good luck!
